name: Auto Assgin Reviewer

on:
  pull_request:
    types: [opened,reopened]
  pull_request_review:
    types: [submitted]

jobs:
  reviewer-assign:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: reviewer-assign
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ toJson(github.event) }}
          echo 'PR Num: ${{ github.event.number }}'
          gh pr edit ${{ github.event.number }} --add-reviewer momiage-man
  reviewer-re-assign:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: reviewer-assign
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ toJson(github.event) }}
          echo 'PR Num: ${{ github.event.number }}'
          gh pr edit ${{ github.event.number }} --add-reviewer momiage-man
