name: Auto Assgin Reviewer

on:
  pull_request:
    types: [opened,reopened]
  pull_request_review:
    types: [submitted]

jobs:
  reviewer-assign:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: reviewer-assign
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "PR Num: $PR_NUMBER"
          gh pr edit $PR_NUMBER --add-reviewer momiage-man
  reviewer-re-assign:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: reviewer-assign
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |

          echo "PR Num: $PR_NUMBER"
          gh pr edit $PR_NUMBER --add-reviewer momiage-man
